version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/var/www/html'
    depends_on:
      - mysql
    container_name: project_app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  composer:
    image: composer:1.6
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    command: composer install
